% Problem 2 Part B
clear all;

img = imread('Text-CCITT.tif');

maxRunLength = size(img, 2);
runCountHisto0 = zeros(maxRunLength, 1);
runCountHisto1 = zeros(maxRunLength, 1);
% For length purposes, the runlengths of black and white pixels can be kept
% as separate arrays for easier processing
runCounts0 = [];
runCounts1 = [];
% If the run count is positive, it's a run of white pixels. If it's negative,
% it's a run of black pixels.
runCounts = [];

% Count the number of runs
for ii=1:size(img,1)
    runCount = 1;
    for jj=1:size(img,2)-1
        % Check if run continues
        if img(ii,jj+1) == img(ii,jj)
            runCount = runCount + 1;
        % Current run has ended, save and start a new run
        else
            % A black run
            if img(ii, jj) == 0
                %runCountHisto0(runCount) = runCountHisto0(runCount) + 1;
                runCounts0 = [runCounts0 runCount];
                runCounts = [runCounts -runCount];
            % A white run
            else
                %runCountHisto1(runCount) = runCountHisto1(runCount) + 1;
                runCounts1 = [runCounts1 runCount];
                runCounts = [runCounts runCount];
            end
            runCount = 1;
        end
    end
    % End of line, save accordingly
    if img(ii, jj) == 0
        %runCountHisto0(runCount) = runCountHisto0(runCount) + 1;
        runCounts0 = [runCounts0 runCount];
        runCounts = [runCounts -runCount];
    else
        %runCountHisto1(runCount) = runCountHisto1(runCount) + 1;
        runCounts1 = [runCounts1 runCount];
        runCounts = [runCounts runCount];
    end
end


%% Start doing Golomb coding and count the word lengths

% Init values
A = 5;
Nmax = 100;
N = 1;
totalLength0 = 0;
% Start counting the encoded codelengths for 0-bit runlengths
for ii = 1:length(runCounts0)
    r = runCounts0(ii);
    [codelength, A, N] = golombAdaptiveLength(r-1, A, N, Nmax);
    totalLength0 = totalLength0 + codelength;
end

fprintf('Text-CCITT.tif: For Nmax = %i, runs of 0''s requires %i bits\n', Nmax, totalLength0);

% Init values
A = 5;
Nmax = 100;
N = 1;
totalLength1 = 0;
% Start counting the encoded codelengths for 1-bit runlengths
for ii = 1:length(runCounts1)
    r = runCounts1(ii);
    [codelength, A, N] = golombAdaptiveLength(r-1, A, N, Nmax);
    totalLength1 = totalLength1 + codelength;
end

fprintf('Text-CCITT.tif: For Nmax = 100, runs of 1''s requires %i bits\n', totalLength1);

compressRatio = numel(img)/(totalLength0 + totalLength1);

fprintf('Text-CCITT.tif: Compression ratio is: %6.4f\n', compressRatio);

%% Problem 3 Part b.ii

xNmax = 10:10:500;
yBits0 = zeros(length(xNmax), 1);
yBits1 = zeros(length(xNmax), 1);

% Get the data for the 0-bit runs
for ii=1:length(xNmax)
    % Initialize values
    A = 5;
    Nmax = xNmax(ii);
    N = 1;
    totalLength0 = 0;
    % Start counting the encoded codelengths for 0-bit runlengths
    for jj = 1:length(runCounts0)
        r = runCounts0(jj);
        [codelength, A, N] = golombAdaptiveLength(r-1, A, N, Nmax);
        totalLength0 = totalLength0 + codelength;
    end
    yBits0(ii) = totalLength0;
end

% Get the data for the 1-bit runs
for ii=1:length(xNmax)
    % Initialize values
    A = 5;
    Nmax = xNmax(ii);
    N = 1;
    totalLength1 = 0;
    % Start counting the encoded codelengths for 0-bit runlengths
    for jj = 1:length(runCounts1)
        r = runCounts1(jj);
        [codelength, A, N] = golombAdaptiveLength(r-1, A, N, Nmax);
        totalLength1 = totalLength1 + codelength;
    end
    yBits1(ii) = totalLength1;
end

figure, plot(xNmax, yBits0), title('N_max vs bits required for 0s');
figure, plot(xNmax, yBits1), title('N_max vs bits required for 1s');

yBits0minIdx = find(yBits0==min(yBits0), 1);
yBits1minIdx = find(yBits1==min(yBits1), 1);
minNmax0 = xNmax(yBits0minIdx);
minNmax1 = xNmax(yBits1minIdx);
minBitsReq0 = yBits0(yBits0minIdx);
minBitsReq1 = yBits1(yBits1minIdx);

fprintf('Text-CCITT.tif: Nmax that minimizes output bits for runs of 0 is %i\n', minNmax0)
fprintf('Text-CCITT.tif: Number of bits generated by Golomb coding for runs of 0 is %i\n', minBitsReq0);
fprintf('Text-CCITT.tif: Nmax that minimizes output bits for runs of 1 is %i\n', minNmax1) 
fprintf('Text-CCITT.tif: Number of bits generated by Golomb coding for runs of 1 is %i\n', minBitsReq1);